IGNITE-27579 C++ Client: Use CPack to generate installation packages (#7487)
Co-authored-by: dzabotlin <dzabotlin@gridgain.com>

diff --git a/modules/platforms/cpp/cmake/scripts/odbc/post_install.sh.in b/modules/platforms/cpp/cmake/scripts/odbc/post_install.sh.in
--- a/modules/platforms/cpp/cmake/scripts/odbc/post_install.sh.in
+++ b/modules/platforms/cpp/cmake/scripts/odbc/post_install.sh.in
@@ -1,3 +1,4 @@
+#!/bin/sh
 #
 # Licensed to the Apache Software Foundation (ASF) under one or more
 # contributor license agreements. See the NOTICE file distributed with
@@ -15,24 +16,7 @@
 # limitations under the License.
 #
 
-set(TARGET ignite-protocol)
-
-set(SOURCES
-    sql/column_meta.cpp sql/column_meta.h
-    bitset_span.h
-    buffer_adapter.cpp buffer_adapter.h
-    extension_types.h
-    heartbeat_timeout.h
-    messages.cpp messages.h
-    protocol_context.h
-    protocol_version.cpp protocol_version.h
-    reader.cpp reader.h
-    utils.cpp utils.h
-    writer.cpp writer.h
-)
-
-add_library(${TARGET} OBJECT ${SOURCES})
-target_link_libraries(${TARGET} PUBLIC ignite-common msgpack-c)
-
-set_target_properties(${TARGET} PROPERTIES VERSION ${CMAKE_PROJECT_VERSION})
-set_target_properties(${TARGET} PROPERTIES POSITION_INDEPENDENT_CODE 1)
+if ! odbcinst -i -d -f @IGNITE_ODBC_INI_PATH@/ignite3-odbc.ini -v; then
+    echo "Error: Failed to install Apache Ignite 3 ODBC driver using odbcinst." >&2
+    exit 1
+fi
